version: "3.7"
services:

  service_books:
    build: ./books
    container_name: container_books
    command: gunicorn --bind 0.0.0.0:5000 books:app
    ports:
      - "5000:5000"

  service_consumer:
    build: ./consumer
    container_name: container_consumer
    command: gunicorn --bind 0.0.0.0:5000 consumer:app
    ports:
      - "5001:5000"
